include:
  - '.gitlab/config.yml'

stages:
  - test_gpu
  - train

test_gpu:
  stage: test_gpu
  only:
    #- /^test-.*$/
    - web
    #- schedules # for nightly, not yet implemented
  script:
    - echo "Checking GPU..."
    - nvidia-smi  # Verify GPU is visible
    #- |
    #  python -c 'import torch; print(f"PyTorch CUDA available: {torch.cuda.is_available()}")'
  tags:
    - Gem12Server

train:
  stage: train
  only:
    #- /^test-.*$/
    - web
    #- schedules # for nightly, not yet implemented
  script:
    - echo "Starting training..."
    - mkdir -Force artifacts
    - "& 'C:\\Users\\phamm\\AppData\\Local\\Programs\\Python\\Python310\\python.exe' 'src/Vision_Transformer_Pytorch/train_moe.py' *> 'artifacts/training_log.txt'"
    - echo "Training complete!"
  dependencies:
    - test_gpu
  artifacts:
    paths:
      - artifacts/training_log.txt 
      - artifacts/training_metrics.png
    when: always
    expire_in: 1 week
  tags:
    - Gem12Server
  #only:
    #- schedules  # Only run in CI; skip locally
  timeout: 10h
