include:
  - '.gitlab/config.yml'

variables:

stages:
  - test_gpu
  - prepare
  - train
  #- cleanup

test_gpu:
  stage: test_gpu
  only:
    - web
    #- schedules # for nightly, not yet implemented
  script:
    - echo "Checking GPU..."
    - nvidia-smi
  tags:
    - Gem12Server

prepare:
  stage: prepare
  tags:
    - Gem12Server
  script:
    - echo "Preparing repository..."
    - |
      if (Test-Path "${CI_PROJECT_DIR}/.git") {
          # Repository exists - update it
          echo "Repository already exists, updating..."
          cd ${CI_PROJECT_DIR}
          git fetch origin
          git checkout ${CI_COMMIT_REF_NAME}
          git reset --hard origin/${CI_COMMIT_REF_NAME}
          echo "Repository updated"
      } else {
          # Repository doesn't exist - clone it
          echo "Cloning fresh repository..."
          git clone https://github.com/PMQ9/Mixture-of-Experts_Research.git ${CI_PROJECT_DIR}
          cd ${CI_PROJECT_DIR}
          git checkout ${CI_COMMIT_REF_NAME}
          git reset --hard origin/${CI_COMMIT_REF_NAME}
          echo "Repository cloned"
      }
    - echo "Repository ready at ${CI_PROJECT_DIR}"
  timeout: 30m

train:
  stage: train
  only:
    - web
    #- schedules # for nightly, not yet implemented
  script:
    - echo "Starting training..."
    - cd ${CI_PROJECT_DIR}
    - mkdir -Force artifacts
    #- "& 'C:\\Users\\phamm\\AppData\\Local\\Programs\\Python\\Python310\\python.exe' 'src/Visison_Tranformer_Pytorch/train_moe.py' *> 'artifacts/pipeline_log.txt'" # 2 typos
    - "& 'C:\\Users\\phamm\\AppData\\Local\\Programs\\Python\\Python310\\python.exe' 'src/Visison_Tranformer_Pytorch/train_moe.py' | Tee-Object -FilePath 'artifacts/pipeline_log.txt'"    
    - echo "Training complete!"
  dependencies:
    - test_gpu
    - prepare
  artifacts:
    paths:
      - artifacts/training_log.txt 
      - artifacts/pipeline_log.png
      - artifacts/training_metrics.png
      - artifacts/vit_cifar10_best.pth
    when: always
    expire_in: 1 week
  tags:
    - Gem12Server
  #only:
    #- schedules
  timeout: 10h

#cleanup:
#  stage: cleanup
#  dependencies:
#    - train
#  tags:
#    - Gem12Server
#  script:
#    - echo "Cleaning up working directory..."
#    - |
#      if (Test-Path "${CI_PROJECT_DIR}/CICD") {
#          if (Test-Path "${CI_PROJECT_DIR}/CICD/artifacts") {
#              Move-Item -Path "${CI_PROJECT_DIR}/CICD/artifacts" -Destination "${CI_PROJECT_DIR}/" -Force
#          }
#          Remove-Item -Recurse -Force "${CI_PROJECT_DIR}/CICD"
#          echo "Cleanup complete - removed ${CI_PROJECT_DIR}/CICD"
#      } else {
#          echo "Nothing to clean up - ${CI_PROJECT_DIR}/CICD doesn't exist"
#      }
#  when: always